# tpl-debian-13, VMID 903: the base for dot-debian, the VM dotfiles-Debian's
# bootstrap is tested on (#920, ADR-0090).
#
# Kali's shape (kali.pkr.hcl) with Debian's netinst: the same installer, so
# the same exception to ADR-0074's "answer files on a disc". Debian's
# installer reads a preseed from the install medium or from a URL, not from a
# second disc, so the seed is served from phoenix's HTTP server for the few
# seconds the installer fetches it. That needs phoenix's firewall to admit the
# guest's DHCP address on the port below (build-the-lab-templates.md §5).
#
# Unlike Kali, Secure Boot stays on: Debian ships a Microsoft-signed shim and
# signed kernels, and the clones keep the module's pre-enrolled keys.

source "proxmox-iso" "debian" {
  proxmox_url              = var.proxmox_url
  username                 = var.proxmox_token_id
  token                    = var.proxmox_token_secret
  insecure_skip_tls_verify = var.proxmox_insecure_skip_tls_verify
  node                     = var.node

  vm_id                = 903
  vm_name              = "tpl-debian-13"
  template_name        = "tpl-debian-13"
  template_description = "Debian 13 (trixie), built by packer/debian.pkr.hcl on ${timestamp()}. Full clones only (ADR-0074)."
  tags                 = "template;linux"

  os              = "l26"
  machine         = "q35"
  bios            = "ovmf"
  cpu_type        = "host"
  cores           = 2
  sockets         = 1
  memory          = 4096
  scsi_controller = "virtio-scsi-single"
  qemu_agent      = true

  efi_config {
    efi_storage_pool  = var.disk_storage
    efi_type          = "4m"
    pre_enrolled_keys = true
  }

  disks {
    type         = "scsi"
    storage_pool = var.disk_storage
    disk_size    = "32G"
    format       = "raw"
    io_thread    = true
    discard      = true
    ssd          = true
  }

  network_adapters {
    model    = "virtio"
    bridge   = var.bridge
    firewall = false
  }

  boot_iso {
    type     = "ide"
    index    = "2"
    iso_file = var.debian_iso_file
    unmount  = true
  }

  http_content = {
    "/preseed.cfg" = templatefile("${abspath(path.root)}/debian/preseed.cfg.pkrtpl", {
      ssh_public_key = trimspace(file(pathexpand(var.ssh_public_key_file)))
    })
  }
  http_port_min = 8800
  http_port_max = 8800

  cloud_init              = true
  cloud_init_storage_pool = var.disk_storage
  cloud_init_disk_type    = "ide"

  # The disk first, then the installer, as ubuntu.pkr.hcl explains: without
  # it OVMF can come to GRUB after the boot command was typed into nothing,
  # and after the install's reboot the installer would boot again.
  boot = "order=scsi0;ide2"

  # Debian's EFI GRUB: drop to the prompt and boot the text installer's kernel
  # with the preseed URL, rather than drive the graphical menu. 20s, not
  # Kali's 10: OVMF fails the empty disk first, and on the first build
  # (2026-10-08) the `c` landed before the menu was drawn. The menu has no
  # timeout, so the build sat at it waiting for SSH until the line was typed
  # by hand from the console.
  boot_wait = "20s"
  boot_command = [
    "c<wait3s>",
    "linux /install.amd/vmlinuz auto=true priority=critical ",
    "preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg ",
    "debian-installer/locale=en_US.UTF-8 keyboard-configuration/xkb-keymap=us ",
    "netcfg/get_hostname=tpl-debian-13 netcfg/get_domain= ",
    "--- quiet<enter><wait3s>",
    "initrd /install.amd/initrd.gz<enter><wait3s>",
    "boot<enter>",
  ]

  communicator         = "ssh"
  ssh_username         = "packer"
  ssh_private_key_file = pathexpand(var.ssh_private_key_file)
  ssh_timeout          = "45m"
}

build {
  name    = "debian"
  sources = ["source.proxmox-iso.debian"]

  provisioner "shell" {
    execute_command = "sudo -E sh -eu '{{ .Path }}'"
    inline = [
      "apt-get update",
      "DEBIAN_FRONTEND=noninteractive apt-get -y full-upgrade",
      "DEBIAN_FRONTEND=noninteractive apt-get -y autoremove --purge",
      "apt-get clean",
      # Host keys and machine-id are per-guest. cloud-init regenerates the keys
      # on a clone's first boot; an empty machine-id is regenerated by systemd.
      "rm -f /etc/ssh/ssh_host_*",
      "cloud-init clean --logs --machine-id",
    ]
  }

  # Last: remove the build user, as ubuntu.pkr.hcl does and for its reasons.
  provisioner "shell" {
    execute_command = "sudo -E sh -eu '{{ .Path }}'"
    skip_clean      = true
    inline = [
      "rm -f /etc/sudoers.d/90-packer",
      "userdel -f -r packer || true",
    ]
  }
}
