# tpl-fedora-server, VMID 904: the base for dot-fedora, the VM dotfiles-Fedora's
# bootstrap is tested on (#920, ADR-0090).
#
# Fedora Server's netinst, driven by a kickstart on a disc labelled OEMDRV.
# Anaconda looks for that label at boot and loads its ks.cfg with no `inst.ks`
# argument, so the boot command only has to pick the install entry, and
# nothing listens on phoenix. Server, not Workstation: the Workstation ISO is
# a live image that kickstart does not drive, and the bootstrap is run with
# --no-flatpak on a headless box (dotfiles-Fedora's README).

source "proxmox-iso" "fedora" {
  proxmox_url              = var.proxmox_url
  username                 = var.proxmox_token_id
  token                    = var.proxmox_token_secret
  insecure_skip_tls_verify = var.proxmox_insecure_skip_tls_verify
  node                     = var.node

  vm_id                = 904
  vm_name              = "tpl-fedora-server"
  template_name        = "tpl-fedora-server"
  template_description = "Fedora Server 44, built by packer/fedora.pkr.hcl on ${timestamp()}. Full clones only (ADR-0074)."
  tags                 = "template;linux"

  os              = "l26"
  machine         = "q35"
  bios            = "ovmf"
  cpu_type        = "host"
  cores           = 2
  sockets         = 1
  memory          = 4096
  scsi_controller = "virtio-scsi-single"
  qemu_agent      = true

  efi_config {
    efi_storage_pool  = var.disk_storage
    efi_type          = "4m"
    pre_enrolled_keys = true
  }

  disks {
    type         = "scsi"
    storage_pool = var.disk_storage
    disk_size    = "32G"
    format       = "raw"
    io_thread    = true
    discard      = true
    ssd          = true
  }

  network_adapters {
    model    = "virtio"
    bridge   = var.bridge
    firewall = false
  }

  boot_iso {
    type     = "ide"
    index    = "2"
    iso_file = var.fedora_iso_file
    unmount  = true
  }

  additional_iso_files {
    type             = "ide"
    index            = "0"
    iso_storage_pool = var.iso_storage
    cd_label         = "OEMDRV"
    cd_content = {
      "ks.cfg" = templatefile("${abspath(path.root)}/fedora/ks.cfg.pkrtpl", {
        ssh_public_key = trimspace(file(pathexpand(var.ssh_public_key_file)))
      })
    }
    unmount = true
  }

  cloud_init              = true
  cloud_init_storage_pool = var.disk_storage
  cloud_init_disk_type    = "ide"

  # The disk first, then the installer, as ubuntu.pkr.hcl explains.
  boot = "order=scsi0;ide2"

  # The menu's default is "Test this media & install", a checksum pass over
  # the disc first. Up to "Install Fedora" and go; the kickstart does the rest.
  boot_wait    = "10s"
  boot_command = ["<up><enter>"]

  communicator         = "ssh"
  ssh_username         = "packer"
  ssh_private_key_file = pathexpand(var.ssh_private_key_file)
  ssh_timeout          = "45m"
}

build {
  name    = "fedora"
  sources = ["source.proxmox-iso.fedora"]

  provisioner "shell" {
    execute_command = "sudo -E sh -eu '{{ .Path }}'"
    inline = [
      "dnf -y upgrade --refresh",
      "dnf clean all",
      # Host keys and machine-id are per-guest. cloud-init regenerates the keys
      # on a clone's first boot; an empty machine-id is regenerated by systemd.
      "rm -f /etc/ssh/ssh_host_*",
      "cloud-init clean --logs --machine-id",
    ]
  }

  # Last: remove the build user, as ubuntu.pkr.hcl does and for its reasons.
  provisioner "shell" {
    execute_command = "sudo -E sh -eu '{{ .Path }}'"
    skip_clean      = true
    inline = [
      "rm -f /etc/sudoers.d/90-packer",
      "userdel -f -r packer || true",
    ]
  }
}
