# tpl-ubuntu-2604, VMID 901: the base for alexander, odin, fenrir and whatever
# Linux guest comes next (ADR-0074).
#
# The installer is driven by autoinstall from a disc labelled `cidata`, which
# cloud-init's NoCloud datasource finds by label. No Packer HTTP server, so
# nothing has to listen on phoenix and nothing on VLAN 30 has to reach it.
#
# The template is left with an empty Proxmox cloud-init drive. A clone gets its
# hostname, user, key and address from that drive at first boot, which is what
# makes one template serve every guest.

locals {
  ssh_public_key = trimspace(file(pathexpand(var.ssh_public_key_file)))
}

source "proxmox-iso" "ubuntu" {
  proxmox_url              = var.proxmox_url
  username                 = var.proxmox_token_id
  token                    = var.proxmox_token_secret
  insecure_skip_tls_verify = var.proxmox_insecure_skip_tls_verify
  node                     = var.node

  vm_id                = 901
  vm_name              = "tpl-ubuntu-2604"
  template_name        = "tpl-ubuntu-2604"
  template_description = "Ubuntu Server 26.04, built by packer/ubuntu.pkr.hcl on ${timestamp()}. Full clones only (ADR-0074)."
  tags                 = "template;linux"

  # The guest shape every Linux guest here already has (build-the-jumpbox.md
  # §1), on OVMF so a clone can be given a TPM later without a reinstall.
  os              = "l26"
  machine         = "q35"
  bios            = "ovmf"
  cpu_type        = "host"
  cores           = 2
  sockets         = 1
  memory          = 4096
  scsi_controller = "virtio-scsi-single"
  qemu_agent      = true

  efi_config {
    efi_storage_pool  = var.disk_storage
    efi_type          = "4m"
    pre_enrolled_keys = true
  }

  disks {
    type         = "scsi"
    storage_pool = var.disk_storage
    disk_size    = "32G"
    format       = "raw"
    io_thread    = true
    discard      = true
    ssd          = true
  }

  network_adapters {
    model    = "virtio"
    bridge   = var.bridge
    firewall = false
  }

  boot_iso {
    type     = "ide"
    index    = "2"
    iso_file = var.ubuntu_iso_file
    unmount  = true
  }

  # The autoinstall seed. cidata is the label NoCloud looks for.
  additional_iso_files {
    type             = "ide"
    index            = "0"
    iso_storage_pool = var.iso_storage
    cd_label         = "cidata"
    cd_content = {
      "meta-data" = ""
      "user-data" = templatefile("${abspath(path.root)}/ubuntu/user-data.pkrtpl", {
        ssh_public_key = local.ssh_public_key
      })
    }
    unmount = true
  }

  cloud_init              = true
  cloud_init_storage_pool = var.disk_storage
  cloud_init_disk_type    = "ide"

  # GRUB on OVMF: drop to the GRUB prompt and boot the live kernel with
  # `autoinstall`, which skips the "really wipe the disk?" confirmation.
  boot_wait = "10s"
  boot_command = [
    "c<wait3s>",
    "linux /casper/vmlinuz --- autoinstall<enter><wait3s>",
    "initrd /casper/initrd<enter><wait3s>",
    "boot<enter>",
  ]

  communicator         = "ssh"
  ssh_username         = "packer"
  ssh_private_key_file = pathexpand(var.ssh_private_key_file)
  ssh_timeout          = "45m"
}

build {
  name    = "ubuntu"
  sources = ["source.proxmox-iso.ubuntu"]

  provisioner "shell" {
    execute_command = "sudo -E sh -eu '{{ .Path }}'"
    inline = [
      "cloud-init status --wait || true",
      "apt-get update",
      "DEBIAN_FRONTEND=noninteractive apt-get -y full-upgrade",
      "DEBIAN_FRONTEND=noninteractive apt-get -y autoremove --purge",
      "apt-get clean",
      # The installer leaves config that pins this build's network and tells
      # cloud-init to stand down. A clone needs cloud-init to own both.
      "rm -f /etc/cloud/cloud.cfg.d/99-installer.cfg /etc/cloud/cloud.cfg.d/90-installer-network.cfg /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg",
      "rm -f /etc/netplan/00-installer-config.yaml /etc/netplan/50-cloud-init.yaml",
      # Host keys and machine-id are per-guest. cloud-init regenerates the keys
      # on a clone's first boot; an empty machine-id is regenerated by systemd.
      "rm -f /etc/ssh/ssh_host_*",
      "cloud-init clean --logs --machine-id",
    ]
  }

  # Last: remove the build user. -f because this session is that user's, and
  # skip_clean because the script cannot delete itself from a home directory
  # that no longer exists. The builder then shuts the guest down through the
  # agent and converts it.
  provisioner "shell" {
    execute_command = "sudo -E sh -eu '{{ .Path }}'"
    skip_clean      = true
    inline = [
      "rm -f /etc/sudoers.d/90-packer",
      "userdel -f -r packer || true",
    ]
  }
}
